In [35]:
import pandas as pd
import numpy as np

In [36]:
# Creating Input multi dimensional Array
points = np.array([[1, 0, 1, 1], [2, 1, 0, 2], [2, 2, 2, 1]])
print(points.shape)
print(points)

result = np.array([[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]])

(3, 4)
[[1 0 1 1]
 [2 1 0 2]
 [2 2 2 1]]


In [37]:
# Calculating Euclidean Distance
# distance between (x1, y1) and (x2, y2) is
# sqrt((x1-x2)^2 + (y1-y2)^2)
for i in range(points.shape[0]):
    for j in range(points.shape[0]):
        dist_sum=0
        for k in range(points.shape[1]):
            dist_sum = dist_sum + (points[i][k]-points[j][k])**2
        result[i][j] = np.sqrt(dist_sum)  
print(result)        
        

[[0.         2.         2.44948974]
 [2.         0.         2.44948974]
 [2.44948974 2.44948974 0.        ]]


In [38]:
# Calculating Manhattan Distance
# distance between (x1, y1) and (x2, y2) is
# abs(x1-x2)+abs(y1-y2)
for i in range(points.shape[0]):
    for j in range(points.shape[0]):
        dist_sum=0
        for k in range(points.shape[1]):
            dist_sum = dist_sum + abs(points[i][k]-points[j][k])
        print(dist_sum)
        result[i][j] = dist_sum 
print(result)        
        

0
4
4
4
0
4
4
4
0
[[0. 4. 4.]
 [4. 0. 4.]
 [4. 4. 0.]]


In [ ]:
# Calculating Cosine Distance
# distance between (x1, y1) and (x2, y2) is
# (x1.x2 + y1.y2) / (sqrt(x1^2 + y1^2)* sqrt(x2^2 + y2^2))
for i in range(points.shape[0]):
    for j in range(points.shape[0]):
        dist_sum, n1, d1, d2= 0, 0, 0, 0
        for k in range(points.shape[1]):
            n1 = n1 + abs(points[i][k]*points[j][k])
            d1 = d1 + points[i][k]**2
            d2 = d2 + points[j][k]**2
        d1 = np.sqrt(d1)
        d2 = np.sqrt(d2)
        dist_sum = n1/(d1*d2)
        result[i][j] = dist_sum 
print(result)      